---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreated
  namespace: new-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod
  strategy:
    type: ReCreate
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
        - name: train
          image: luffsenpai/train:REPLACE_TAG
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: my-pod
  ports:
    - port: 80
      targetPort: 8080
