apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreatedep
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
        - name: my-train
          image: dockernaruto1/train-book:REPLACE_TAG
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: my-pod
  ports:
    - port: 80
      targetPort: 8080
