apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-dep
  namespace: new-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-new
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxunavailable: 50%
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: pod-new
    spec:
      containers:
        - name: train
          image: luffsenpai/train:REPLACE_TAG
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: train-service
  namespace: new-namespace
spec:
  type: NodePort
  selector:
    app: pod-new
  ports:
    - port: 80
      targetPort: 8080
